/**
 * generated by Xtext 2.13.0
 */
package dk.sdu.stefh14.math.validation;

import dk.sdu.stefh14.math.validation.AbstractDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DSLValidator extends AbstractDSLValidator {
}
