/*
 * generated by Xtext 2.13.0
 */
package dk.sdu.stefh14.math.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractDSLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(dk.sdu.stefh14.math.dSL.DSLPackage.eINSTANCE);
		return result;
	}
	
}
