/*
 * generated by Xtext 2.13.0
 */
package dk.sdu.stefh14.math.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.AbstractGenerator
import org.eclipse.xtext.generator.IFileSystemAccess2
import org.eclipse.xtext.generator.IGeneratorContext
import javax.swing.JOptionPane
import dk.sdu.stefh14.math.dSL.MathExp
import dk.sdu.stefh14.math.dSL.Exp
import dk.sdu.stefh14.math.dSL.Primary
import dk.sdu.stefh14.math.dSL.Plus
import dk.sdu.stefh14.math.dSL.Minus
import dk.sdu.stefh14.math.dSL.Mult
import dk.sdu.stefh14.math.dSL.Div
import dk.sdu.stefh14.math.dSL.Number;
import dk.sdu.stefh14.math.dSL.Parenthesis;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
class DSLGenerator extends AbstractGenerator {

	override void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
		val math = resource.allContents.filter(MathExp).next
		val result = math.compute
		System.out.println("Math expression = "+math.display)
		JOptionPane.showMessageDialog(null, "result = "+result,"Math Language", JOptionPane.INFORMATION_MESSAGE)
	}
	
	//
	// Compute function: computes value of expression
	// Note: written according to illegal left-recursive grammar, requires fix
	//
	
	def int compute(MathExp math) { 
		math.exp.computeExp
	}
	
	def int computeExp(Exp exp) {
		val left = exp.left.computePrim
		println("computeExp, got left value " + left)
		println("computeExp, has operator: " + exp.operator)
		switch exp.operator {
			Plus: {
				println("computeExp, in Plus")
				left+exp.right.computeExp
			}
			Minus: left-exp.right.computeExp
			Mult: left*exp.right.computeExp
			Div: left/exp.right.computeExp
			default: {
				println("computeExp, in default")
				left
			}
		}
	}
	
	def dispatch int computePrim(Number factor) { 
		println("computePrim, returning " + factor.value)
		factor.value
	}
	
	def dispatch int computePrim(Parenthesis factor) { 
		factor.exp.computeExp
	}

	//
	// Display function: show complete syntax tree
	// Note: written according to illegal left-recursive grammar, requires fix
	//

	def CharSequence display(MathExp math) '''Math[«math.exp.displayExp»]'''
	def CharSequence displayExp(Exp exp) '''Exp[«exp.left.displayPrim»,«exp.operator?.displayOp»,«exp.right?.displayExp»]'''
	def dispatch String displayOp(Plus op)  { "+" }
	def dispatch String displayOp(Minus op) { "-" }
	def dispatch String displayOp(Mult op) { "*" }
	def dispatch String displayOp(Div op) { "/" }
	def CharSequence displayFactor(Primary primary) { "?" }
	def dispatch CharSequence displayPrim(Number prim) '''Num[«prim.value»]'''
	def dispatch CharSequence displayPrim(Parenthesis pare) '''Parenthesis[«pare.exp.displayExp»]'''
	
}
