/*
 * generated by Xtext 2.13.0
 */
package dk.sdu.stefh14.math.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.AbstractGenerator
import org.eclipse.xtext.generator.IFileSystemAccess2
import org.eclipse.xtext.generator.IGeneratorContext
import javax.swing.JOptionPane
import dk.sdu.stefh14.math.dSL.MathExp
import dk.sdu.stefh14.math.dSL.Exp
import dk.sdu.stefh14.math.dSL.Primary
import dk.sdu.stefh14.math.dSL.Plus
import dk.sdu.stefh14.math.dSL.Minus
import dk.sdu.stefh14.math.dSL.Mult
import dk.sdu.stefh14.math.dSL.Div
import dk.sdu.stefh14.math.dSL.Number
import dk.sdu.stefh14.math.dSL.Parenthesis
import dk.sdu.stefh14.math.dSL.Factor

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
class DSLGenerator extends AbstractGenerator {

	override void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
		val math = resource.allContents.filter(MathExp).next
		val result = math.compute
		System.out.println("Math expression = "+math.display)
		JOptionPane.showMessageDialog(null, "result = "+result,"Math Language", JOptionPane.INFORMATION_MESSAGE)
	}
	
	//
	// Compute function: computes value of expression
	//
	
	def int compute(MathExp math) { 
		math.exp.computeExpression
	}
	
	def dispatch int computeExpression(Exp exp) {
		val left = exp.left.computeExpression
		switch exp.operator {
			Plus: left+exp.right.computeExpression
			Minus: left-exp.right.computeExpression
			default: left
		}
	}
	
	def dispatch int computeExpression(Factor fac) {
		val left = fac.left.computeExpression
		switch fac.operator {
			Mult: left*fac.right.computeExpression
			Div: left/fac.right.computeExpression
			default: left
		}
	}
	
	def dispatch int computeExpression(Parenthesis par) {
		par.exp.computeExpression
	}
	
	def dispatch int computeExpression(Number num) {
		num.value
	}

	//
	// Display function: show complete syntax tree
	//

	def CharSequence display(MathExp math) '''Math[«math.exp.displayExp»]'''
	def dispatch CharSequence displayExp(Exp exp) '''Exp[«exp.left.displayExp»,«exp.operator?.displayOp»,«exp.right?.displayExp»]'''
	def dispatch CharSequence displayExp(Factor exp) '''Factor[«exp.left.displayExp»,«exp.operator?.displayOp»,«exp.right?.displayExp»]'''
	def dispatch CharSequence displayExp(Number prim) '''Num[«prim.value»]'''
	def dispatch CharSequence displayExp(Parenthesis pare) '''Parenthesis[«pare.exp.displayExp»]'''
	def dispatch String displayOp(Plus op)  { "+" }
	def dispatch String displayOp(Minus op) { "-" }
	def dispatch String displayOp(Mult op) { "*" }
	def dispatch String displayOp(Div op) { "/" }
	def CharSequence displayFactor(Primary primary) { "?" }
	
}
