/**
 * generated by Xtext 2.13.0
 */
package dk.sdu.stefh14.math.tests;

import com.google.inject.Inject;
import dk.sdu.stefh14.math.tests.DSLInjectorProvider;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(DSLInjectorProvider.class)
@SuppressWarnings("all")
public class DSLParsingTest {
  @Inject
  private /* ParseHelper<Model> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field DSLParsingTest.parseHelper refers to the missing type Model"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\njoin cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
}
