/**
 * generated by Xtext 2.13.0
 */
package dk.sdu.stefh14.math.ui;

import dk.sdu.stefh14.math.ui.AbstractDSLUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DSLUiModule extends AbstractDSLUiModule {
  public DSLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
