/**
 * generated by Xtext 2.13.0
 */
package dk.sdu.stefh14.math.ide;

import dk.sdu.stefh14.math.ide.AbstractDSLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DSLIdeModule extends AbstractDSLIdeModule {
}
