/**
 * generated by Xtext 2.13.0
 */
package dk.sdu.stefh14.math.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import dk.sdu.stefh14.math.DSLRuntimeModule;
import dk.sdu.stefh14.math.DSLStandaloneSetup;
import dk.sdu.stefh14.math.ide.DSLIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class DSLIdeSetup extends DSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    DSLRuntimeModule _dSLRuntimeModule = new DSLRuntimeModule();
    DSLIdeModule _dSLIdeModule = new DSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_dSLRuntimeModule, _dSLIdeModule));
  }
}
