/*
 * generated by Xtext 2.13.0
 */
package dk.sdu.stefh14.math.ui;

import com.google.inject.Injector;
import dk.sdu.stefh14.math.ui.internal.MathActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(MathActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		MathActivator activator = MathActivator.getInstance();
		return activator != null ? activator.getInjector(MathActivator.DK_SDU_STEFH14_MATH_DSL) : null;
	}

}
