/**
 * generated by Xtext 2.13.0
 */
package dk.sdu.stefh14.math.dSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exp Op</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.stefh14.math.dSL.DSLPackage#getExpOp()
 * @model
 * @generated
 */
public interface ExpOp extends EObject
{
} // ExpOp
