/**
 * generated by Xtext 2.13.0
 */
package dk.sdu.stefh14.math.dSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parenthesis</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.stefh14.math.dSL.Parenthesis#getExp <em>Exp</em>}</li>
 * </ul>
 *
 * @see dk.sdu.stefh14.math.dSL.DSLPackage#getParenthesis()
 * @model
 * @generated
 */
public interface Parenthesis extends Primary
{
  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exp</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(Exp)
   * @see dk.sdu.stefh14.math.dSL.DSLPackage#getParenthesis_Exp()
   * @model containment="true"
   * @generated
   */
  Exp getExp();

  /**
   * Sets the value of the '{@link dk.sdu.stefh14.math.dSL.Parenthesis#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(Exp value);

} // Parenthesis
