/**
 * generated by Xtext 2.13.0
 */
package dk.sdu.stefh14.math.dSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Plus</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.stefh14.math.dSL.DSLPackage#getPlus()
 * @model
 * @generated
 */
public interface Plus extends ExpOp
{
} // Plus
