/**
 * generated by Xtext 2.13.0
 */
package dk.sdu.stefh14.math.ui.contentassist;

import dk.sdu.stefh14.math.ui.contentassist.AbstractDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DSLProposalProvider extends AbstractDSLProposalProvider {
}
