/**
 * generated by Xtext 2.13.0
 */
package dk.sdu.stefh14.math.dSL.impl;

import dk.sdu.stefh14.math.dSL.DSLPackage;
import dk.sdu.stefh14.math.dSL.Plus;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Plus</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PlusImpl extends ExpOpImpl implements Plus
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PlusImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DSLPackage.Literals.PLUS;
  }

} //PlusImpl
