/*
 * generated by Xtext 2.13.0
 */
package dk.sdu.stefh14.math.ui.tests;

import com.google.inject.Injector;
import dk.sdu.stefh14.math.ui.internal.MathActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class DSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MathActivator.getInstance().getInjector("dk.sdu.stefh14.math.DSL");
	}

}
