/**
 * generated by Xtext 2.13.0
 */
package dk.sdu.stefh14.math.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class DSLDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
