/**
 * generated by Xtext 2.13.0
 */
package dk.sdu.stefh14.math.scoping;

import dk.sdu.stefh14.math.scoping.AbstractDSLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class DSLScopeProvider extends AbstractDSLScopeProvider {
}
