grammar dk.sdu.stefh14.math.DSL with org.eclipse.xtext.common.Terminals

generate dSL "http://www.sdu.dk/stefh14/math/DSL"

MathExp:
	'result' 'is' exp=Exp
;

Exp:
	Factor ({Exp.left=current} operator=ExpWeakOp right=Exp)?
;

Factor:
	Primary ({Factor.left=current} operator=ExpStrongOp right=Factor)?
;

ExpWeakOp:
	{Plus} '+' | {Minus} '-'	
;

ExpStrongOp:
	{Mult} '*' | {Div} '/'
;

Primary:
	Number | Parenthesis
;

Parenthesis:
	'(' exp=Exp ')'
;

Number:
	value=INT
;