/**
 * generated by Xtext 2.13.0
 */
package dk.sdu.stefh14.math;

import dk.sdu.stefh14.math.AbstractDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DSLRuntimeModule extends AbstractDSLRuntimeModule {
}
