/**
 * generated by Xtext 2.13.0
 */
package dk.sdu.stefh14.math;

import dk.sdu.stefh14.math.DSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DSLStandaloneSetup extends DSLStandaloneSetupGenerated {
  public static void doSetup() {
    new DSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
