/*
 * generated by Xtext 2.13.0
 */
package dk.sdu.stefh14.math2.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class DSLUiModule extends AbstractDSLUiModule {
}
