/*
 * generated by Xtext 2.13.0
 */
package dk.sdu.stefh14.math.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDSLScopeProvider extends DelegatingScopeProvider {
}
